version: '3.9'

services:
  db:
    image: postgres:15
    container_name: ecommerce_db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  redis:
    image: redis:7
    container_name: ecommerce_redis
    ports:
      - '6380:6379'
    networks:
      - ecommerce_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce_rabbitmq
    ports:
      - '5672:5672' # Broker port
      - '15672:15672' # Management UI
    networks:
      - ecommerce_network

  web:
    build:
      context: .
    container_name: ecommerce_web
    command: >
      sh -c "python manage.py makemigrations store &&
         python manage.py migrate --database=default &&
         python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - ecommerce_network

  celery:
    build:
      context: .
    container_name: ecommerce_celery
    command: celery -A backend worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
    networks:
      - ecommerce_network

volumes:
  postgres_data:

networks:
  ecommerce_network:
    driver: bridge
