[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"

[[services]]
name = "web"
httpPort = 8000
startCommand = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"

[[services]]
name = "celery"
startCommand = "celery -A backend worker --loglevel=info"